### ISSUE TITLE
Couldn't render

### ISSUE THREAD

**Issue by yuehhuahii** [JuliaNeuralGraphics/GaussianSplatting.jl#11]
Hi! I'm appreciate of your great work!
It comes to me that the GUI is forced terminated while rendering the bicycle dataset.

![螢幕快照 2024-09-03 15-20-39](https://github.com/user-attachments/assets/70dfd54d-bc5a-41f0-adde-4f666ee572fa)

![螢幕快照 2024-09-03 15-21-07](https://github.com/user-attachments/assets/903952f2-6370-47c6-906c-490f1ee8cc5e)

Any idea?

My hardware information:
OS: EndeavourOS 2024.01.25
GPU: NVIDIA GeForce RTX 4070 Laptop GPU, 8 GB memory

**Comment by pxl-th** [comment]
I suspect it shows a message like "Window is not responsive" or something like that.
In some way this is expected, but should dissapear after some time.
This is because Julia is JIT compiled, so when you launch the application it compiles GPU kernels as it launches them for the first time.

On my machine the window becomes responsive again in around 30-40 seconds. Does that happen on your machine?

**Comment by pxl-th** [comment]
The UX definitely can be improved, for example by compiling in a background thread while should some progress bar to the user.

**Comment by yuehhuahii** [comment]
Yeah, the window message shows "Window is not responsive".
So, I have to wait for it for aound 30-40 seconds, right?
I didn't wait and just terminate the window.

**Comment by pxl-th** [comment]
Yes, that should work

**Comment by yuehhuahii** [comment]
Thank you so much! It works!
